In [1]:
import pandas as pd

In [2]:
import csv

file_path = r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\project.csv"

project = pd.read_csv(
    file_path,
    sep=';',
    quoting=csv.QUOTE_ALL,
    encoding='utf-8',
    on_bad_lines='skip'
)

project.head()

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,nature,objective,contentUpdateDate,rcn,grantDoi
0,672641,ADHESION,CLOSED,Development of new biotech AdvanceD materials ...,2015-05-01,2015-10-31,71429,50000,H2020-EU.2.1.4.,BIOTEC-5a-2014-1,2015-04-17,H2020,H2020-SMEInst-2014-2015,H2020-SMEINST-1-2014,SME-1,NaN,The aim of the ADHESION Project is to strength...,2024-09-06 18:16:22,196463,10.3030/672641
1,750248,GlycoNanoPep,CLOSED,Glyco and Nano Peptide Conjugates for Selectiv...,2017-04-01,2019-03-31,"158121,6","158121,6",H2020-EU.1.3.,MSCA-IF-2016,2017-02-27,H2020,H2020-MSCA-IF-2016,H2020-MSCA-IF-2016,MSCA-IF-EF-ST,NaN,The next generation therapeutic agents such as...,2022-08-16 00:01:34,208681,10.3030/750248
2,855867,NANOFLOWSIZER,CLOSED,Developing a disruptive and revolutionary tool...,2019-03-01,2019-06-30,71429,50000,H2020-EU.2.3.,EIC-SMEInst-2018-2020,2019-02-05,H2020,H2020-EIC-SMEInst-2018-2020,H2020-SMEInst-2018-2020-1,SME-1,NaN,Nanotechnology is rapidly growing in the pharm...,2024-09-06 17:42:42,221149,10.3030/855867
3,778157,CanBioSe,SIGNED,Novel 1D photonic metal oxide nanostructures f...,2018-01-01,2023-12-31,1116000,1116000,H2020-EU.1.3.,MSCA-RISE-2017,2017-11-22,H2020,H2020-MSCA-RISE-2017,H2020-MSCA-RISE-2017,MSCA-RISE,NaN,The project CanBioSe targeted to strengthen in...,2025-02-19 12:25:10,213008,10.3030/778157
4,798830,MAGNET-CELLPATCH,CLOSED,Multimodal magnetic cellular-patches with syne...,2019-09-01,2021-08-31,"158121,6","158121,6",H2020-EU.1.3.,MSCA-IF-2017,2018-03-19,H2020,H2020-MSCA-IF-2017,H2020-MSCA-IF-2017,MSCA-IF-EF-ST,NaN,The key goals of the MAGNET-CELLPATCH project ...,2022-08-24 00:16:07,215681,10.3030/798830

In [3]:
file_path = r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\topics.csv"

topics = pd.read_csv(
    file_path,
    sep=';',
    quoting=csv.QUOTE_ALL,
    encoding='utf-8',
    on_bad_lines='skip'
)

topics.head()

,projectID,topic,title
0,672641,BIOTEC-5a-2014-1,SME boosting biotechnology-based industrial pr...
1,816332,EIC-SMEInst-2018-2020,SME instrument
2,750248,MSCA-IF-2016,Individual Fellowships
3,855867,EIC-SMEInst-2018-2020,SME instrument
4,778157,MSCA-RISE-2017,Research and Innovation Staff Exchange

In [4]:
file_path = r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\euroSciVoc.csv"

euroSciVoc = pd.read_csv(
    file_path,
    sep=';',
    quoting=csv.QUOTE_ALL,
    encoding='utf-8',
    on_bad_lines='skip'
)

euroSciVoc.head()

,projectID,euroSciVocCode,euroSciVocPath,euroSciVocTitle,euroSciVocDescription
0,672641,/25/75/469,/engineering and technology/mechanical enginee...,manufacturing engineering,NaN
1,672641,/21/39/223,/medical and health sciences/clinical medicine...,surgery,NaN
2,672641,/23/53/365/72505310,/natural sciences/chemical sciences/inorganic ...,transition metals,NaN
3,672641,/25/69/435,/engineering and technology/nanotechnology/nan...,nano-materials,NaN
4,672641,/21/39/221,/medical and health sciences/clinical medicine...,cardiology,NaN

In [5]:
file_path = r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\legalBasis.csv"

legalBasis = pd.read_csv(
    file_path,
    sep=';',
    quoting=csv.QUOTE_ALL,
    encoding='utf-8',
    on_bad_lines='skip'
)

legalBasis.head()

,projectID,legalBasis,title,uniqueProgrammePart
0,672641,H2020-EU.2.1.4.,INDUSTRIAL LEADERSHIP - Leadership in enabling...,True
1,672641,H2020-EU.2.3.1.,"Mainstreaming SME support, especially through...",NaN
2,816332,H2020-EU.3.,PRIORITY 'Societal challenges,NaN
3,816332,H2020-EU.2.3.,INDUSTRIAL LEADERSHIP - Innovation In SMEs,True
4,816332,H2020-EU.2.1.,INDUSTRIAL LEADERSHIP - Leadership in enabling...,NaN

In [6]:
file_path = r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\projectPublications.csv"

projectPublications = pd.read_csv(
    file_path,
    sep=';',
    quoting=csv.QUOTE_ALL,
    encoding='utf-8',
    on_bad_lines='skip'
)

projectPublications.head()

C:\Users\jawri\AppData\Local\Temp\ipykernel_17372\138010392.py:3: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  projectPublications = pd.read_csv(

,id,title,isPublishedAs,authors,journalTitle,journalNumber,publishedYear,publishedPages,issn,isbn,doi,projectID,projectAcronym,collection,contentUpdateDate,rcn
0,951475_2590757_PUBLI,A multiplex protein panel assay for severity p...,Peer reviewed articles,"Ziyue Wang, Adam Cryar, Oliver Lemke, Pinkus T...",eClinicalMedicine,49,2023.0,101495,2589-5370,NaN,10.1016/j.eclinm.2022.101495,951475,FungalTolerance,Project publication,2025-04-22 19:52:40,1286170
1,825664_2581201_PUBLI,The global Alzheimer's Association round robin...,Peer reviewed articles,"Josef Pannee, Leslie M. Shaw, Magdalena Koreck...","Alzheimer's & Dementia: Diagnosis, Assessment ...",13,2023.0,NaN,2352-8729,NaN,10.1002/dad2.12242,825664,JPCOFUND2,Project publication,2025-04-22 19:49:42,1285553
2,825664_2581050_PUBLI,Head-to-Head Comparison of 8 Plasma Amyloid-β ...,Peer reviewed articles,"Shorena Janelidze, Charlotte E. Teunissen, Hen...",JAMA Neurology,78,2023.0,1375,2168-6149,NaN,10.1001/jamaneurol.2021.3180,825664,JPCOFUND2,Project publication,2025-04-22 19:49:40,1285545
3,825664_2580833_PUBLI,Human Small Heat Shock Protein B8 Inhibits Pro...,Peer reviewed articles,"Dhawal Choudhary, Laura Mediani, Mario J. Avel...",Journal of the American Chemical Society,145,2023.0,15188-15196,0002-7863,NaN,10.1021/jacs.3c02022,825664,JPCOFUND2,Project publication,2025-04-22 19:49:33,1285517
4,825546_2551530_PUBLI,Diet and exercise in frailty and sarcopenia. M...,Peer reviewed articles,"Fernando Millan-Domingo, Esther Garcia-Domingu...",Molecular Aspects of Medicine,100,2024.0,101322,0098-2997,NaN,10.1016/j.mam.2024.101322,825546,DIABFRAIL-LATAM,Project publication,2025-04-22 19:49:31,1285508

In [7]:
file_path = r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\projectIrps_h2020.csv"

projectIrps = pd.read_csv(
    file_path,
    sep=',',
    quoting=csv.QUOTE_ALL,
    encoding='utf-8',
    on_bad_lines='skip'
)

projectIrps.head()

,projectID,type,title,organisationID,applicantName,applicationDate,applicationPrefix,applicationIdentifier,applicationKind,epoAppUrl,priorityDate,patentType,awardDate,awardPrefix,awardIdentifier,awardKind,epoPubUrl,patentFamilyIdentifier
0,641518,PATENT,Method for the acquisition and processing of g...,996169922.0,GEONUMERICS SL,2013-07-22,US,201314417435,A,https://worldwide.espacenet.com/patent/search?...,2012-07-26,BACKGROUND,2015-07-09,US,2015192928,A1,https://worldwide.espacenet.com/patent/search?...,47528706.0
1,635734,PATENT,KETOREDUCTASES,986597283.0,C-LECTA GMBH,2017-07-14,EP,2018069058,W,https://worldwide.espacenet.com/patent/search?...,NaN,BACKGROUND,2019-01-17,WO,2019012095,A1,https://worldwide.espacenet.com/patent/search?...,62837946.0
2,653203,PATENT,Mecanisme de pivotement de dossier de siege,999420877.0,PSA AUTOMOBILES SA,2015-04-08,FR,1553008,A,https://worldwide.espacenet.com/patent/search?...,NaN,BACKGROUND,2018-10-12,FR,3034721,B1,https://worldwide.espacenet.com/patent/search?...,53514331.0
3,653203,PATENT,Ouvrant en élytre vers l'arrière,999420877.0,PSA AUTOMOBILES SA,2016-06-26,FR,1651536,A,https://worldwide.espacenet.com/patent/search?...,NaN,BACKGROUND,2018-02-23,FR,3048202,B1,https://worldwide.espacenet.com/patent/search?...,56117860.0
4,653203,PATENT,Système de fixation et de réglage du dossier p...,999420877.0,PSA AUTOMOBILES SA,2015-05-21,FR,1554570,A,https://worldwide.espacenet.com/patent/search?...,NaN,BACKGROUND,2017-06-02,FR,3036365,B1,https://worldwide.espacenet.com/patent/search?...,53758419.0

In [8]:
file_path = r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\organization.csv"

organization = pd.read_csv(
    file_path,
    sep=';',
    quoting=csv.QUOTE_ALL,
    encoding='utf-8',
    on_bad_lines='skip'
)

organization.head()

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,672641,ADHESION,969027576,IT01949700221,NOVAGENIT SRL,NOVAGENIT SRL,True,PRC,VIALE TRENTO 115/117,38017,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-09-06 18:16:22,1936887,1,coordinator,50000.0,50000.0,71429,False,NaN
1,816332,OILCS,927067995,NaN,FIRMA INSTYTUT ECOLOGII LIUDYNY-INEKO,FIRM INSTITUTE OF HUMAN ECOLOGY-INEKO,True,PRC,82 ALISHER NAVOI AVE APT 15 DNIPROVSKYI DISTRICT,02125,...,https://ec.europa.eu/info/funding-tenders/oppo...,2022-08-12 11:39:44,2470604,1,coordinator,50000.0,50000.0,71429,False,NaN
2,750248,GlycoNanoPep,999829635,ESQ1518001A,UNIVERSIDAD DE SANTIAGO DE COMPOSTELA,UNIVERSIDADE DE SANTIAGO DE COMPOSTELA,False,HES,COLEXIO DE SAN XEROME PRAZA DO OBRADOIRO S/N,15782,...,https://ec.europa.eu/info/funding-tenders/oppo...,2022-08-16 00:01:34,1907764,1,coordinator,158121.6,158121.6,"158121,6",False,NaN
3,855867,NANOFLOWSIZER,918624727,NL854200484B01,INPROCESS-LSP BV,NaN,True,PRC,KLOOSTERSTRAAT 9,5349 AB,...,https://ec.europa.eu/info/funding-tenders/oppo...,2024-09-06 17:42:42,1956205,1,coordinator,50000.0,50000.0,71429,False,NaN
4,778157,CanBioSe,952695492,NaN,NANOPHARMA AS,NANOPHARMA AS,True,PRC,NOVA 306,530 09,...,https://ec.europa.eu/info/funding-tenders/oppo...,2025-02-19 12:25:10,2200531,8,participant,9000.0,9000.0,9000,False,NaN

In [9]:
# Drop duplicate projects
project = project.drop_duplicates(subset='id')

# Convert dates
project['startDate'] = pd.to_datetime(project['startDate'], errors='coerce')
project['endDate'] = pd.to_datetime(project['endDate'], errors='coerce')
project['duration_months'] = (project['endDate'] - project['startDate']).dt.days // 30

# Convert to numeric
project['ecMaxContribution'] = pd.to_numeric(project['ecMaxContribution'], errors='coerce')
project['totalCost'] = pd.to_numeric(project['totalCost'], errors='coerce')

# Drop rows missing key info
project = project.dropna(subset=['id', 'totalCost', 'duration_months'])

# Keep only projects with positive total cost and nonzero duration
project = project[(project['totalCost'] > 0) & (project['duration_months'] > 0)]

In [10]:
# keep only the columns needed for building features
# drop rows that are missing key info
# remove exact duplicates
# tidy text formatting in activityType and country
org_trimmed = organization[['projectID', 'organisationID', 'country', 'activityType', 'SME']]
org_trimmed = org_trimmed.dropna(subset=['projectID', 'country', 'activityType'])
org_trimmed = org_trimmed.drop_duplicates()
org_trimmed['activityType'] = org_trimmed['activityType'].str.strip().str.upper()
org_trimmed['country'] = org_trimmed['country'].str.strip().str.upper()

In [11]:
# count how many of each partner type (HES, PRC, etc.) are in each project
# reset index so projectID becomes a column again
partner_types = pd.crosstab(org_trimmed['projectID'], org_trimmed['activityType'])
partner_types = partner_types.reset_index()
partner_types.columns = ['projectID'] + [f'partnertype_{col}' for col in partner_types.columns[1:]]

In [12]:
# show the first few rows of partner type counts
partner_types.head()

,projectID,partnertype_HES,partnertype_OTH,partnertype_PRC,partnertype_PUB,partnertype_REC
0,115797,27,1,8,3,5
1,115842,7,0,2,1,3
2,115843,6,2,4,0,6
3,115844,1,1,1,0,1
4,115847,1,4,1,0,0

In [13]:
# create a new table showing whether each project involves any SME
# each row = one project; has_sme is True if any partner is an SME
sme_flag = org_trimmed.groupby('projectID')['SME'].apply(lambda x: any(x == True)).reset_index()
sme_flag = sme_flag.rename(columns={'SME': 'has_sme'})
sme_flag.head()

   projectID  has_sme
0     115797     True
1     115842     True
2     115843     True
3     115844     True
4     115847    False

In [14]:
# Create a new table showing how many partners from each country are involved in each project
country_flags = pd.crosstab(org_trimmed['projectID'], org_trimmed['country']).reset_index()

# Rename columns to add 'country_' prefix (except 'projectID')
country_flags.columns = ['projectID'] + [f"country_{col}" for col in country_flags.columns if col != 'projectID']

# Preview
country_flags.head()

,projectID,country_AE,country_AI,country_AL,country_AM,country_AO,country_AR,country_AT,country_AU,country_AZ,...,country_VE,country_VG,country_VN,country_VU,country_WF,country_XK,country_YE,country_ZA,country_ZM,country_ZW
0,115797,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,115842,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,115843,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,115844,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,115847,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
# merge partner types, SME flag, and country flags into one table
project_features = partner_types.merge(sme_flag, on='projectID', how='left')
project_features = project_features.merge(country_flags, on='projectID', how='left')

# check result
project_features.head()

,projectID,partnertype_HES,partnertype_OTH,partnertype_PRC,partnertype_PUB,partnertype_REC,has_sme,country_AE,country_AI,country_AL,...,country_VE,country_VG,country_VN,country_VU,country_WF,country_XK,country_YE,country_ZA,country_ZM,country_ZW
0,115797,27,1,8,3,5,True,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,115842,7,0,2,1,3,True,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,115843,6,2,4,0,6,True,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,115844,1,1,1,0,1,True,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,115847,1,4,1,0,0,False,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
euroSciVoc.head()

,projectID,euroSciVocCode,euroSciVocPath,euroSciVocTitle,euroSciVocDescription
0,672641,/25/75/469,/engineering and technology/mechanical enginee...,manufacturing engineering,NaN
1,672641,/21/39/223,/medical and health sciences/clinical medicine...,surgery,NaN
2,672641,/23/53/365/72505310,/natural sciences/chemical sciences/inorganic ...,transition metals,NaN
3,672641,/25/69/435,/engineering and technology/nanotechnology/nan...,nano-materials,NaN
4,672641,/21/39/221,/medical and health sciences/clinical medicine...,cardiology,NaN

In [17]:
# Step 1: Split topic paths into Level_1, Level_2, Level_3
euroSciVoc[['Level_1', 'Level_2', 'Level_3']] = euroSciVoc['euroSciVocPath'].str.strip('/').str.split('/', expand=True)[[0, 1, 2]]

# Step 2: Keep one row per project–level combination (we assume each row is already per project-topic pair)
lvl1 = euroSciVoc[['projectID', 'Level_1']].dropna().drop_duplicates()
lvl2 = euroSciVoc[['projectID', 'Level_2']].dropna().drop_duplicates()
lvl3 = euroSciVoc[['projectID', 'Level_3']].dropna().drop_duplicates()

# Step 3: One-hot encode each level
lvl1_encoded = pd.get_dummies(lvl1['Level_1'], prefix='topiclvl1')
lvl1_encoded['projectID'] = lvl1['projectID'].values

lvl2_encoded = pd.get_dummies(lvl2['Level_2'], prefix='topiclvl2')
lvl2_encoded['projectID'] = lvl2['projectID'].values

lvl3_encoded = pd.get_dummies(lvl3['Level_3'], prefix='topiclvl3')
lvl3_encoded['projectID'] = lvl3['projectID'].values

# Step 4: Aggregate back to project-level by grouping and summing
lvl1_flags = lvl1_encoded.groupby('projectID').sum().reset_index()
lvl2_flags = lvl2_encoded.groupby('projectID').sum().reset_index()
lvl3_flags = lvl3_encoded.groupby('projectID').sum().reset_index()

# Step 5: Merge all levels into one table
topic_flags = lvl1_flags.merge(lvl2_flags, on='projectID', how='outer') \
                        .merge(lvl3_flags, on='projectID', how='outer') \
                        .fillna(0)

# ✅ Preview
print(f"✅ Topic columns created: {topic_flags.shape[1] - 1}")
topic_flags.head()

✅ Topic columns created: 299

,projectID,topiclvl1_agricultural sciences,topiclvl1_engineering and technology,topiclvl1_humanities,topiclvl1_medical and health sciences,topiclvl1_natural sciences,topiclvl1_social sciences,topiclvl2_agricultural biotechnology,"topiclvl2_agriculture, forestry, and fisheries",topiclvl2_animal and dairy science,...,topiclvl3_urology,topiclvl3_vehicle engineering,topiclvl3_venereal diseases,topiclvl3_visual arts,topiclvl3_waste management,topiclvl3_water engineering,topiclvl3_water treatment processes,topiclvl3_wearable medical technology,topiclvl3_woodworking,topiclvl3_zoology
0,115797,0,0,0,1,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,115842,0,0,0,1,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,115843,0,0,0,1,1,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,115844,0,1,0,1,1,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,115847,0,1,0,1,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# Convert all columns except 'projectID' to integer
for col in topic_flags.columns:
    if col != 'projectID':
        topic_flags[col] = topic_flags[col].astype(int)

# Rename final table
topic_dummies = topic_flags.copy()

# ✅ Confirm shape and types
print("✅ Topic dummies prepared.")
print("📊 Shape:", topic_dummies.shape)
print("🔠 Dtypes:")
print(topic_dummies.dtypes.value_counts())

✅ Topic dummies prepared.
📊 Shape: (32149, 300)
🔠 Dtypes:
int32    299
int64      1
Name: count, dtype: int64

In [19]:
project_features = project_features.merge(topic_dummies, on='projectID', how='left')

In [20]:
# convert to numeric, force bad values to NaN
cols = ['totalCost', 'ecMaxContribution', 'duration_months']
for col in cols:
    project[col] = pd.to_numeric(project[col], errors='coerce')

# now drop rows where any of those are missing or not valid
project = project.dropna(subset=cols)

# drop any rows where values are 0 or negative
project = project[
    (project['totalCost'] > 0) &
    (project['ecMaxContribution'] > 0) &
    (project['duration_months'] > 0)
]

In [21]:
project[['totalCost', 'ecMaxContribution', 'duration_months']].skew()

totalCost            25.698262
ecMaxContribution    25.358785
duration_months       0.018467
dtype: float64

In [22]:
# Ensure projectID columns are both strings
project_features['projectID'] = project_features['projectID'].astype(str)
project['id'] = project['id'].astype(str)

# Drop existing versions of these columns if they’re already in the table
columns_to_merge = ['duration_months', 'totalCost', 'ecMaxContribution']
project_features = project_features.drop(columns=[col for col in columns_to_merge if col in project_features.columns])

# Perform the merge cleanly
project_features = project_features.merge(
    project.rename(columns={'id': 'projectID'})[['projectID'] + columns_to_merge],
    on='projectID',
    how='left'
)

# Drop rows with missing key project data
project_features = project_features.dropna(subset=columns_to_merge)

print("✅ Metadata merged and cleaned.")

✅ Metadata merged and cleaned.

In [23]:
# Extract the base project ID from the full ID values like "825664_2581201_PUBL"
projectPublications['projectID'] = projectPublications['projectID'].astype(str).str.extract(r'^(\d+)')

# Keep only unique project–DOI pairs
unique_pubs = projectPublications[['projectID', 'doi']].drop_duplicates()

# Count how many unique publications each project has
pub_counts = unique_pubs.groupby('projectID').size().reset_index(name='num_publications')

# Ensure projectID is str in both tables
pub_counts['projectID'] = pub_counts['projectID'].astype(str)
project_features['projectID'] = project_features['projectID'].astype(str)

# Drop existing 'num_publications' column if it exists (for safe re-runs)
if 'num_publications' in project_features.columns:
    project_features = project_features.drop(columns=['num_publications'])

# Merge publication counts
project_features = project_features.merge(
    pub_counts,
    on='projectID',
    how='left'
)

# Fill missing counts with 0
project_features['num_publications'] = project_features['num_publications'].fillna(0).astype(int)

print("✅ Cleaned and merged publication counts.")

✅ Cleaned and merged publication counts.

In [24]:
pub_counts['num_publications'].skew()

99.33397491936294

In [25]:
# Add total partner count
partner_cols = [col for col in project_features.columns if col.startswith('partnertype_')]
project_features['total_partners'] = project_features[partner_cols].sum(axis=1)

In [26]:
# Fill all NaNs in full feature table with 0
project_features = project_features.fillna(0)
# Convert all topic columns to int
topic_cols = [col for col in project_features.columns if col.startswith('topic')]
project_features[topic_cols] = project_features[topic_cols].astype(int)
#all columns in wide DataFrame

print(project_features.columns)

Index(['projectID', 'partnertype_HES', 'partnertype_OTH', 'partnertype_PRC',
       'partnertype_PUB', 'partnertype_REC', 'has_sme', 'country_AE',
       'country_AI', 'country_AL',
       ...
       'topiclvl3_water engineering', 'topiclvl3_water treatment processes',
       'topiclvl3_wearable medical technology ', 'topiclvl3_woodworking',
       'topiclvl3_zoology', 'duration_months', 'totalCost',
       'ecMaxContribution', 'num_publications', 'total_partners'],
      dtype='object', length=486)

In [27]:
# Drop duplicate patents per project (e.g. same awardIdentifier)
deduped_patents = projectIrps.drop_duplicates(subset=['projectID', 'awardIdentifier'])

# Count patents per project
patent_counts = deduped_patents.groupby('projectID').size().reset_index(name='num_patents')

# Ensure consistent dtype
project_features['projectID'] = project_features['projectID'].astype(str)
patent_counts['projectID'] = patent_counts['projectID'].astype(str)

# Merge with feature set
project_features = project_features.merge(patent_counts, on='projectID', how='left')

# Fill missing values with 0
project_features['num_patents'] = project_features['num_patents'].fillna(0).astype(int)

In [28]:
# Load citation data from full path
citations = pd.read_csv(r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\alex\project_citations.csv")

# Drop duplicate project–DOI pairs
citations = citations.drop_duplicates(subset=['projectID', 'doi'])

# Clean projectID column (remove quotes, strip)
citations['projectID'] = citations['projectID'].astype(str).str.strip('"').str.strip()

# Group and sum citation counts per project
citation_counts = citations.groupby('projectID')['cited_by_count'].sum().reset_index()

# Check unique character lengths
citations['projectID'] = citations['projectID'].astype(str).str.strip()
citations['id_length'] = citations['projectID'].str.len()

# See how many have expected length (e.g., 6 or more digits)
print(citations['id_length'].value_counts())

id_length
6      278032
9       17593
0        1569
4         441
1         286
        ...
120         1
121         1
112         1
127         1
141         1
Name: count, Length: 146, dtype: int64

In [29]:
valid_ids = set(project_features['projectID'])
present_ids = set(citations['projectID'])

# % match
match_pct = 100 * len(present_ids & valid_ids) / len(present_ids)
print(f"{match_pct:.2f}% of citation projectIDs are found in project_features")

37.78% of citation projectIDs are found in project_features

In [30]:
# Ensure strings and strip spaces
projectPublications['projectID'] = projectPublications['projectID'].astype(str).str.strip()
project_features['projectID'] = project_features['projectID'].astype(str).str.strip()

# Calculate match percentage
match_pct = 100 * projectPublications['projectID'].isin(project_features['projectID']).mean()
print(f"{match_pct:.2f}% of projectPublications IDs are found in project_features")

49.59% of projectPublications IDs are found in project_features

In [31]:
# Show first few rows
print(citations.head(20))

    projectID                            doi  cited_by_count  id_length
0      951475   10.1016/j.eclinm.2022.101495            28.0          6
1      825664             10.1002/dad2.12242            28.0          6
2      825664   10.1001/jamaneurol.2021.3180           341.0          6
3      825664           10.1021/jacs.3c02022             7.0          6
4      825546      10.1016/j.mam.2024.101322             4.0          6
5      956454  10.1016/j.jclepro.2023.139482             9.0          6
6      956439         10.1002/cctc.202400215             1.0          6
7      899546              10.1111/gcb.17312            32.0          6
8      890284     10.1038/s41598-022-22258-1            17.0          6
9      852187     10.1038/s41467-024-48571-z            10.0          6
10     851555    10.1051/0004-6361/202449203             0.0          6
11     823878       10.1088/1402-4896/ad2b34             2.0          6
12  101007896       10.1088/1402-4896/ad2b34             2.0          9
13     864361     10.1038/s41586-023-06718-w            15.0          6
14     864299         10.1002/aelm.202201160             7.0          6
15     951747         10.1002/aelm.202201160             7.0          6
16     823947       10.3390/universe10020058             0.0          6
17     823893   10.1021/acs.jmedchem.4c01368             3.0          6
18     957755     10.1016/j.segy.2024.100155             0.0          6
19     952911         10.1021/acsami.3c04282             5.0          6

In [66]:
# Clean DOIs first
citations['doi'] = citations['doi'].astype(str).str.lower().str.strip()
projectPublications['doi'] = projectPublications['doi'].astype(str).str.lower().str.strip()

# Merge citation data onto publications by DOI
pubs_with_citations = projectPublications.merge(
    citations[['doi', 'cited_by_count']],
    on='doi',
    how='left'
)

# Fill null citation counts
pubs_with_citations['cited_by_count'] = pubs_with_citations['cited_by_count'].fillna(0).astype(int)

# Group citation count by projectID
project_citations = pubs_with_citations.groupby('projectID')['cited_by_count'].sum().reset_index(name='num_citations')

# Merge onto features
project_features = project_features.merge(
    project_citations,
    on='projectID',
    how='left'
)

# Fill missing projects with 0
project_features['num_citations'] = project_features['num_citations'].fillna(0).astype(int)

print("✅ Merged citation counts into project_features via publication DOIs.")

✅ Merged citation counts into project_features via publication DOIs.

In [68]:
# Check % of project IDs in pubs_with_citations that match project_features
valid_ids = set(project_features['projectID'])
present_ids = set(pubs_with_citations['projectID'])

match_pct = 100 * len(present_ids & valid_ids) / len(present_ids)
print(f"🔎 {match_pct:.2f}% of projects with DOIs and citation data are found in project_features")

🔎 42.19% of projects with DOIs and citation data are found in project_features

In [70]:
# Ensure clean formats
citations['projectID'] = citations['projectID'].astype(str).str.strip().str.extract(r'^(\d+)')
projectPublications['projectID'] = projectPublications['projectID'].astype(str).str.strip().str.extract(r'^(\d+)')

# Compare sets
pub_ids = set(projectPublications['projectID'])
cit_ids = set(citations['projectID'])

# Check match %
match_pct = 100 * len(cit_ids & pub_ids) / len(cit_ids)
print(f"{match_pct:.2f}% of citation projectIDs are found in projectPublications")

98.26% of citation projectIDs are found in projectPublications

In [74]:
columns_list = list(project_features.columns)
for col in columns_list:
    print(col)

projectID
partnertype_HES
partnertype_OTH
partnertype_PRC
partnertype_PUB
partnertype_REC
has_sme
country_AE
country_AI
country_AL
country_AM
country_AO
country_AR
country_AT
country_AU
country_AZ
country_BA
country_BD
country_BE
country_BF
country_BG
country_BH
country_BI
country_BJ
country_BO
country_BQ
country_BR
country_BT
country_BW
country_BY
country_BZ
country_CA
country_CD
country_CG
country_CH
country_CI
country_CL
country_CM
country_CN
country_CO
country_CR
country_CU
country_CV
country_CY
country_CZ
country_DE
country_DJ
country_DK
country_DO
country_DZ
country_EC
country_EE
country_EG
country_EL
country_ES
country_ET
country_FI
country_FJ
country_FO
country_FR
country_GA
country_GD
country_GE
country_GH
country_GI
country_GL
country_GT
country_HK
country_HN
country_HR
country_HU
country_ID
country_IE
country_IL
country_IN
country_IQ
country_IR
country_IS
country_IT
country_JE
country_JM
country_JO
country_JP
country_KE
country_KG
country_KH
country_KR
country_KW
country_KZ
country_LA
country_LB
country_LI
country_LK
country_LR
country_LS
country_LT
country_LU
country_LV
country_LY
country_MA
country_MC
country_MD
country_ME
country_MG
country_MH
country_MK
country_ML
country_MM
country_MN
country_MR
country_MT
country_MU
country_MV
country_MW
country_MX
country_MY
country_MZ
country_NC
country_NE
country_NG
country_NI
country_NL
country_NO
country_NP
country_NZ
country_OM
country_PA
country_PE
country_PF
country_PG
country_PH
country_PK
country_PL
country_PS
country_PT
country_PY
country_QA
country_RO
country_RS
country_RU
country_RW
country_SA
country_SB
country_SC
country_SD
country_SE
country_SG
country_SI
country_SK
country_SL
country_SN
country_SR
country_ST
country_SX
country_SZ
country_TD
country_TG
country_TH
country_TJ
country_TM
country_TN
country_TR
country_TW
country_TZ
country_UA
country_UG
country_UK
country_UM
country_US
country_UY
country_UZ
country_VA
country_VE
country_VG
country_VN
country_VU
country_WF
country_XK
country_YE
country_ZA
country_ZM
country_ZW
topiclvl1_agricultural sciences
topiclvl1_engineering and technology
topiclvl1_humanities
topiclvl1_medical and health sciences
topiclvl1_natural sciences
topiclvl1_social sciences
topiclvl2_agricultural biotechnology
topiclvl2_agriculture, forestry, and fisheries
topiclvl2_animal and dairy science
topiclvl2_arts
topiclvl2_basic medicine
topiclvl2_biological sciences
topiclvl2_chemical engineering
topiclvl2_chemical sciences
topiclvl2_civil engineering
topiclvl2_clinical medicine
topiclvl2_computer and information sciences
topiclvl2_earth and related environmental sciences
topiclvl2_economics and business
topiclvl2_educational sciences
topiclvl2_electrical engineering, electronic engineering, information engineering
topiclvl2_environmental biotechnology
topiclvl2_environmental engineering
topiclvl2_health sciences
topiclvl2_history and archaeology
topiclvl2_industrial biotechnology
topiclvl2_languages and literature
topiclvl2_law
topiclvl2_materials engineering
topiclvl2_mathematics
topiclvl2_mechanical engineering
topiclvl2_media and communications
topiclvl2_medical biotechnology
topiclvl2_medical engineering
topiclvl2_nanotechnology
topiclvl2_other engineering and technologies
topiclvl2_other humanities
topiclvl2_other medical sciences
topiclvl2_other social sciences
topiclvl2_philosophy, ethics and religion
topiclvl2_physical sciences
topiclvl2_political sciences
topiclvl2_psychology
topiclvl2_social geography
topiclvl2_sociology
topiclvl2_veterinary sciences
topiclvl3_acoustics
topiclvl3_admiralty law
topiclvl3_agricultural genetics
topiclvl3_agriculture
topiclvl3_air pollution engineering
topiclvl3_allergology
topiclvl3_anaesthesiology
topiclvl3_analytical chemistry
topiclvl3_anatomy and morphology
topiclvl3_andrology
topiclvl3_angiology
topiclvl3_anthropology
topiclvl3_apiculture
topiclvl3_applied mathematics
topiclvl3_applied mechanics
topiclvl3_archaeology
topiclvl3_architectural design
topiclvl3_architecture engineering
topiclvl3_art history
topiclvl3_artificial intelligence
topiclvl3_astronomy
topiclvl3_atmospheric sciences
topiclvl3_atomic physics
topiclvl3_behavioural psychology
topiclvl3_biochemical engineering
topiclvl3_biochemistry
topiclvl3_biodiversity conservation
topiclvl3_biological behavioural sciences
topiclvl3_biological morphology
topiclvl3_biomass
topiclvl3_biomaterials
topiclvl3_biophysics
topiclvl3_bioprocessing technologies
topiclvl3_bioremediation
topiclvl3_biosensing
topiclvl3_botany
topiclvl3_business and management
topiclvl3_carbon capture engineering
topiclvl3_cardiology
topiclvl3_catalysis
topiclvl3_cell biology
topiclvl3_cells technologies
topiclvl3_ceramics
topiclvl3_chemical process engineering
topiclvl3_classical mechanics
topiclvl3_clinical microbiology
topiclvl3_clinical neurology
topiclvl3_coating and films
topiclvl3_cognitive psychology
topiclvl3_colors
topiclvl3_composites
topiclvl3_computational science
topiclvl3_computer security
topiclvl3_condensed matter physics
topiclvl3_constitutional law
topiclvl3_construction engineering
topiclvl3_criminology
topiclvl3_critical care medicine
topiclvl3_crystals
topiclvl3_cultural and economic geography
topiclvl3_dairy
topiclvl3_data science
topiclvl3_databases
topiclvl3_demography
topiclvl3_dermatology
topiclvl3_developmental biology
topiclvl3_developmental psychology
topiclvl3_diagnostic imaging
topiclvl3_didactics
topiclvl3_dietetics
topiclvl3_domestic animals
topiclvl3_ecology
topiclvl3_economics
topiclvl3_ecosystem-based management
topiclvl3_electrical engineering
topiclvl3_electrochemistry
topiclvl3_electromagnetism and electronics
topiclvl3_electronic engineering
topiclvl3_embryology
topiclvl3_emergency medicine
topiclvl3_endocrinology
topiclvl3_energy and fuels
topiclvl3_environmental sciences
topiclvl3_ergonomics
topiclvl3_ethics
topiclvl3_evolutionary biology
topiclvl3_family studies
topiclvl3_fibers
topiclvl3_fisheries
topiclvl3_food technology
topiclvl3_forensic sciences
topiclvl3_forestry
topiclvl3_freshwater biology
topiclvl3_gastroenterology
topiclvl3_gender studies
topiclvl3_general language studies
topiclvl3_general medicine
topiclvl3_genetic engineering
topiclvl3_genetics
topiclvl3_geochemistry
topiclvl3_geological engineering
topiclvl3_geology
topiclvl3_geophysics
topiclvl3_geotechnics
topiclvl3_gerontology
topiclvl3_globalization
topiclvl3_governance
topiclvl3_government systems
topiclvl3_graphic design
topiclvl3_gynaecology
topiclvl3_health care sciences
topiclvl3_health care services
topiclvl3_hematology
topiclvl3_hepatology
topiclvl3_histology
topiclvl3_history
topiclvl3_history of medicine
topiclvl3_human rights
topiclvl3_hydrology
topiclvl3_ideologies
topiclvl3_immunology
topiclvl3_implants
topiclvl3_inclusive education
topiclvl3_industrial relations
topiclvl3_infectious diseases
topiclvl3_inflammatory diseases
topiclvl3_information engineering
topiclvl3_inorganic chemistry
topiclvl3_integrative and complementary medicine
topiclvl3_internal medicine
topiclvl3_international law
topiclvl3_internet
topiclvl3_journalism
topiclvl3_knowledge engineering
topiclvl3_law enforcement
topiclvl3_library sciences
topiclvl3_linguistics
topiclvl3_liquid crystals
topiclvl3_literature studies
topiclvl3_manufacturing engineering
topiclvl3_marine biology
topiclvl3_mechatronics
topiclvl3_medical ethics
topiclvl3_medical genetics
topiclvl3_medical laboratory technology
topiclvl3_medicinal chemistry
topiclvl3_metabolic engineering
topiclvl3_metallurgy
topiclvl3_microbiology
topiclvl3_microtechnology
topiclvl3_mining and mineral processing
topiclvl3_modern and contemporary art
topiclvl3_molecular and chemical physics
topiclvl3_molecular biology
topiclvl3_musicology
topiclvl3_nano-materials
topiclvl3_nano-processes
topiclvl3_nanocomposites
topiclvl3_nanoelectromechanical systems
topiclvl3_nanoelectronics
topiclvl3_nanomedicine
topiclvl3_nanophotonics
topiclvl3_natural resources management
topiclvl3_nephrology
topiclvl3_neurobiology
topiclvl3_neurology
topiclvl3_nuclear chemistry
topiclvl3_nuclear engineering
topiclvl3_nuclear physics
topiclvl3_nursing
topiclvl3_nutrition
topiclvl3_obstetrics
topiclvl3_oceanography
topiclvl3_odontology
topiclvl3_oncology
topiclvl3_ophthalmology
topiclvl3_optics
topiclvl3_organic chemistry
topiclvl3_orthopaedics
topiclvl3_other biological topics
topiclvl3_otorhinolaryngology
topiclvl3_paediatrics
topiclvl3_palaeontology
topiclvl3_parasitology
topiclvl3_pathology
topiclvl3_pedagogy
topiclvl3_penology
topiclvl3_performing arts
topiclvl3_peripheral vascular disease
topiclvl3_personalized medicine
topiclvl3_pharmacology and pharmacy
topiclvl3_philosophy
topiclvl3_physical chemistry
topiclvl3_physical geography
topiclvl3_physiology
topiclvl3_physiotherapy
topiclvl3_plasma physics
topiclvl3_pneumology
topiclvl3_political communication
topiclvl3_political policies
topiclvl3_political transitions
topiclvl3_polymer sciences
topiclvl3_psychiatry
topiclvl3_psycholinguistics
topiclvl3_psychotherapy
topiclvl3_public administration
topiclvl3_public health
topiclvl3_pure mathematics
topiclvl3_quantum physics
topiclvl3_radiology
topiclvl3_relativistic mechanics
topiclvl3_religions
topiclvl3_remote sensing
topiclvl3_reproductive biology
topiclvl3_rheumatology
topiclvl3_separation technologies
topiclvl3_social biomedical sciences
topiclvl3_social issues
topiclvl3_social psychology
topiclvl3_social work
topiclvl3_software
topiclvl3_soil sciences
topiclvl3_special education
topiclvl3_speech-language pathology
topiclvl3_sport and fitness sciences
topiclvl3_structural engineering
topiclvl3_substance abuse
topiclvl3_surgery
topiclvl3_synthetic biology
topiclvl3_synthetic dyes
topiclvl3_textiles
topiclvl3_theoretical physics
topiclvl3_thermodynamic engineering
topiclvl3_thermodynamics
topiclvl3_tissue engineering
topiclvl3_toxicology
topiclvl3_transplantation
topiclvl3_transport
topiclvl3_transportation engineering
topiclvl3_tribology
topiclvl3_tropical medicine
topiclvl3_urban engineering
topiclvl3_urban studies
topiclvl3_urology
topiclvl3_vehicle engineering
topiclvl3_venereal diseases
topiclvl3_visual arts
topiclvl3_waste management
topiclvl3_water engineering
topiclvl3_water treatment processes
topiclvl3_wearable medical technology
topiclvl3_woodworking
topiclvl3_zoology
duration_months
totalCost
ecMaxContribution
num_publications
total_partners
num_patents
num_citations

In [76]:
# Check for missing values
missing_summary = project_features.isnull().sum()
print(missing_summary[missing_summary > 0])

Series([], dtype: int64)

In [80]:
print(project_features.dtypes)

projectID             object
partnertype_HES        int64
partnertype_OTH        int64
partnertype_PRC        int64
partnertype_PUB        int64
                      ...
ecMaxContribution    float64
num_publications       int32
total_partners         int64
num_patents            int32
num_citations          int32
Length: 488, dtype: object

In [82]:
dupes = project_features['projectID'].duplicated().sum()
print(f"Duplicate projectIDs: {dupes}")

Duplicate projectIDs: 0

In [84]:
print(f"Duplicate rows: {project_features.duplicated().sum()}")

Duplicate rows: 0

In [86]:
corr = project_features.corr(numeric_only=True)
print(corr['num_citations'].sort_values(ascending=False))

num_citations                        1.000000
num_publications                     0.547488
num_patents                          0.294314
partnertype_HES                      0.257082
ecMaxContribution                    0.238582
                                       ...
country_WF                                NaN
country_YE                                NaN
topiclvl3_admiralty law                   NaN
topiclvl3_other biological topics         NaN
topiclvl3_venereal diseases               NaN
Name: num_citations, Length: 487, dtype: float64

In [88]:
# Add total_output column
project_features['total_output'] = (
    project_features['num_publications'] +
    project_features['num_citations'] +
    project_features['num_patents']
)

# Save clean feature table
project_features.to_csv('project_features_clean.csv', index=False)

In [94]:
import pandas as pd
import numpy as np


# Load and process the original project table
project = pd.read_csv(r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\project.csv", sep=';', encoding='utf-8', on_bad_lines='skip')
project['endDate'] = pd.to_datetime(project['endDate'], errors='coerce')
today = pd.to_datetime("2025-07-01")
project['months_since_end'] = ((today - project['endDate']).dt.days // 30)

# Count how many projects are missing a months_since_end value
missing_months = project['months_since_end'].isna().sum()
print(f"Projects with undetermined months_since_end: {missing_months}")

Projects with undetermined months_since_end: 11

In [96]:
project['months_since_end'] = project['months_since_end'].fillna(-1).astype(int)
project = project[~project['months_since_end'].isna()]

In [104]:
features = pd.read_csv(r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\project_features_clean.csv")

features = features.merge(
    project[['id', 'months_since_end']],
    left_on='projectID', right_on='id', how='left'
)

features = features.drop(columns=['id'])

In [106]:
features.to_csv(r"C:\Users\jawri\Data course\Capstone\CORDIS data\Projects\project_features_clean.csv", index=False)

In [108]:
row_count = features.shape[0]
print(f"Total number of rows: {row_count}")

Total number of rows: 16584